### ISSUE TITLE
open error with UE5.2

### ISSUE THREAD

**Issue by luoww1992** [4Players/odin-unreal-ovrlipsync#1]
likes title, so it need other plugins?

**Comment by DavidLiebemann** [comment]
Hi! I'll take a look at it. It shouldn't throw any errors, all necessary Plugins are included in the project. Can you share a picture of the error or an error description?

**Comment by luoww1992** [comment]
@SciCoderG 
i try to uninstall vs2019 and install it again, then it is OK!
